djangoapp/blog/urls.py
from django.urls import path
from blog.views import PageDeatailView, PostDeatailView, AuthorsListView, CategoriesListView, TagsListView, SearchListView, IndexListView

app_name = 'blog'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('page/<slug:slug>/', PageDeatailView.as_view(), name='page'),
    path('post/<slug:slug>/', PostDeatailView.as_view(), name='post'),
    path('authors/<int:author_id>/', AuthorsListView.as_view(), name='authors'),
    path('categories/<slug:slug>/', CategoriesListView.as_view(), name='categories'),
    path('tags/<slug:slug>/', TagsListView.as_view(), name='tags'),
    path('search/', SearchListView.as_view(), name='search'),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoapp/blog/models.py
from django.db import models
from utils.random_letters import slugfy_new
from django.contrib.auth.models import User
from utils.resize_images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse

class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name
        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)

        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name
        
        if file_changed:
            resize_image(image_django=self.file, new_width=900, quality=70)

        return super_save


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True, blank=True, default=None, null=True, max_length=128)

    def save(self, *args, **kwargs):
        if not self.slug:
             self.slug = slugfy_new(self.name, 5)

        return super().save(*args, **kwargs)


    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True, blank=True, default=None, null=True, max_length=128)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug =  slugfy_new(self.name, 5)

        return super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return self.name


class Page(models.Model):
    class Meta:
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    title = models.CharField(max_length=64)
    slug = models.SlugField(unique=True, default="", null=False, blank=True, max_length=128)
    is_published = models.BooleanField(default=False, help_text='A página somente será exibida caso essa opção esteja marcada')
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        else:
            return reverse('blog:page', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugfy_new(self.title, 5)

        return super().save(*args, **kwargs)
    

    def __str__(self) -> str:
        return self.title
    

class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-pk')   


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    objects = PostManager()

    title = models.CharField(max_length=64)
    slug = models.SlugField(unique=True, default="", null=False, blank=True, max_length=128)
    summary = models.CharField(max_length=128)
    is_published = models.BooleanField(default=False, help_text='O post somente será exibida caso essa opção esteja marcada')
    content = models.TextField(null=True, blank=True, default=None)

    cover = models.ImageField(upload_to='posts/%Y/%m/', blank=True, default=None)
    cover_in_post_content = models.BooleanField(default=True, help_text='A capa somente será exibida dentro do post caso essa opção esteja marcada')

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='post_created_by')

    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='post_updated_by')

    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    tags = models.ManyToManyField(Tag, blank=True, default=None)

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        else:
            return reverse('blog:post', args=(self.slug,))
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugfy_new(self.title, 5)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)

        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name
        
        if cover_changed:
            resize_image(image_django=self.cover, new_width=900, quality=70)

        return super_save

    def __str__(self) -> str:
        return self.title

djangoapp/blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import redirect
from django.db.models import Q
from blog.models import Post, Page, Tag
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import ListView, DetailView

PER_PAGE = 9

class IndexListView(ListView):
    template_name = 'blog/pages/index.html'
    context_object_name = 'posts'
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)

        context.update({'windowTitle': 'Home - '})

        return context


class AuthorsListView(IndexListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_vars = {}

    def get(self, request, *args, **kwargs):
        author_id = self.kwargs.get('author_id')
        user = User.objects.filter(id=author_id).first()
        
        if user is None:

            raise Http404

        self._temp_vars.update({
            'author_id': author_id, 
            'user': user,
            })
        
        return super().get(request, *args, **kwargs)    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  
        
        user = self._temp_vars['user']
        user_full_name = f'{user.first_name} {user.last_name}' if user.first_name else user.username

        page_title = f'Posts de {user_full_name} -'

        
        context.update({'windowTitle': page_title})

        return context
    
    def get_queryset(self):
        querryset = super().get_queryset()
        author_id = self._temp_vars['author_id']
        querryset = querryset.filter(created_by__id=author_id)

        return querryset


class CategoriesListView(IndexListView):
    allow_empty = False
    
    
    def get_queryset(self) -> QuerySet[Any]:
        slug = self.kwargs.get('slug')
        return super().get_queryset().filter(category__slug=slug)
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = f'Categorias - {self.object_list[0].category} - '
        
        context.update({'windowTitle': page_title})
        return context
        

class TagsListView(IndexListView):
    allow_empty = False
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        slug = self.kwargs.get('slug')
        name = Tag.objects.filter(slug=slug).first().name
        page_title = f'Tags - {name} - '
        

        context.update({'windowTitle': page_title})
        return context
    
    
    def get_queryset(self):
        slug = self.kwargs.get('slug')
        
        return super().get_queryset().filter(tags__slug=slug)


class SearchListView(IndexListView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._search_value = ''
    
        
    def setup(self, request, *args, **kwargs):
        self._search_value = request.GET.get('search').strip()
        return super().setup(request, *args, **kwargs)
    
    
    def get(self, request, *args, **kwargs):
        if self._search_value == '':
            return redirect('blog:index') 
        return super().get(request, *args, **kwargs)
        
    
    def get_queryset(self):
        return super().get_queryset().filter(Q(title__icontains=self._search_value) | Q(summary__icontains=self._search_value))[:PER_PAGE]
    
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = f'{self._search_value[0:30]} - '
        context.update({'windowTitle': page_title, 'search_value': self._search_value})
        return context


class PageDeatailView(DetailView):
    template_name = 'blog/pages/page.html'
    model = Page
    slug_field = 'slug'
    context_object_name = 'page'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        page = self.get_object()
        page_title = f'{page.title} - '
        context.update({'windowTitle': page_title})
        
        return context
    
    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(is_published=True)


class PostDeatailView(DetailView):
    template_name = 'blog/pages/post.html'
    model = Post
    context_object_name = 'post'

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().filter(is_published=True)
    
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        
        post = self.get_object()
        page_title = f'{post.title} - '
        
        ctx.update({'windowTitle': page_title})
        
        return ctx

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">

        {% if posts %}
          <div class="card-grid">
            {% for post in posts %}
              {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
            {% endfor %}
          </div>
        {% else %}
          <div class="not-found center">
            <h1>Nada encontrado</h1>
            <p>Clique <a href="{% url "blog:index" %}">aqui</a> para voltar para a página inicial</p>
          </div>

        {% endif %}

      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center"> {{ page.title }}</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium eaque placeat, optio architecto dignissimos est iure ipsum, iste doloribus dolorum nostrum veniam aspernatur adipisci eos et ab facilis, fugit labore!</p>
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
        <div class="single-post-cover pb-base">
          <img loading="lazy" src="{{ post.cover.url }}" alt="{{ post.tile }}">
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.tile }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url "blog:authors" post.created_by.id %}">
            <i class="fa-solid fa-user"></i>
            <span>
              {% if post.created_by.first_name%}
                {{ post.created_by.first_name }} {{post.created_by.last_name}}
              {% else %}
                {{ post.created_by}}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <spam class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{ post.created_at | date:"d/m/Y \à\s H:i"}}
            </span>
          </spam>
        </div>
        
        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url "blog:categories" post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{post.category}}
              </span>
            </a>
          </div>
        {% endif %}
      </div>
      

      <p class="single-post-excerpt pb-base">
        {{ post.summary | safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content | safe }}
      
      
      {% if post.tags.exists %}
        <div class="post-tags">
          <span>Tags: </span>

          {% for tag in post.tags.all  %}
            <a class="post-tag-link" href="{% url "blog:tags" tag.slug %}">
              <i class="fa-solid fa-link"></i>
              <span>{{ tag.name }}</span>
            </a>
          {% endfor %}
        </div>
      {% endif %}

      </div>
    
    </div>
  </div>
</main>

{% endblock content %}